config/routes.rb
Rails.application.routes.draw do

  get 'shifts/index'

  get 'home/index'

  root to: 'home#index'
  resources :shifts, only: [:index, :create]
  get '/clock_out', to: 'shifts#clock_out'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shifts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def index
    @shifts = current_user.shifts
  end

  def new
    @shift = Shift.new
  end

  def create
    # Note: this is set to EST, would be useful with more time to
    # set login-time to the Users current timezone.
    @shift = Shift.new(
      user_id: current_user.id,
      time_in: Time.now.in_time_zone('Eastern Time (US & Canada)')
      )
    start_shift(@shift)
  end

  def start_shift(shift)
    if shift.save
      current_user.clocked_in = true
      current_user.save
      redirect_to root_url
    else
      render :new
      flash[:alert] = "Unable to start shift."
     end
  end

  def clock_out
    # Note: Same as mentioned on line 13
    @shift = current_user.shifts.all.last
    @shift.time_out = Time.now.in_time_zone('Eastern Time (US & Canada)')
    end_shift(@shift)
  end

  def end_shift(shift)
    if shift.save
      current_user.clocked_in = false
      current_user.save
      redirect_to root_url
    else
      flash[:alert] = "Unable to clockout."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/home/_clock_out.html.erb
<div class="container">
  <% if current_user.shifts.any? %>
    <% time_clocked_in = current_user.shifts.all.last.time_in %>
    <h2>Clocked in at: <%= time_clocked_in.strftime("%I:%M %p") %> </h2>
    <%= button_to "Clock out", clock_out_path, class: "clock-in-btn", method: :get %>
  <% end %>
</div>

app/views/home/_new.html.erb
<div class="container">
  <h1>Hello, <%= current_user.email %></h1>
  <%= button_to "Clock in", shifts_path, class: "clock-in-btn", method: :create %>
</div>

app/views/home/_table.html.erb
<h2 class="table-header">Previous Shifts:</h2>
<div class="table-container">
  <table>
    <tr>
      <th>Clocked In:</th>
      <th>Clocked Out:</th>
      <th>Shift Duration:</th>
    </tr>
    <% current_user.shifts.each do |shift| %>
    <tr>
      <td><%= shift.time_in.strftime("%I:%M %p") %></td>
      <% if shift.time_out.nil? %>
        <td>Still active</td>
        <td> - </td>
      <% else %>
        <td><%= shift.time_out.strftime("%I:%M %p") %></td>
        <% duration = (shift.time_out - shift.time_in).to_i %>
        <td><%= Time.at(duration).utc.strftime("%H:%M:%S") %></td>
      <% end %>
    </tr>
  <% end %>
  </table>
</div>

app/views/home/index.html.erb
<section id="home-page">
  <div class="container">
    <!-- New User Registration -->
    <% if !user_signed_in? %>
      <h1 class="header">Welcome to
        <span class="header-text">CL<i class="far fa-clock"></i>CKIN</span>
      </h1>
      <h2 class="not-signed-up">Not signed up yet?</h2>
      <%= button_to "Sign Up Here!", new_user_registration_path, class: "log-btn sign-up", method: :get %>

    <!-- Main application -->
    <% else %>
      <% if !current_user.clocked_in %>
        <%= render 'new' %>
      <% else %>
        <%= render 'clock_out' %>
      <% end %>
      <!-- We're showing login information only when the user has
      logged existing shifts, and when the user is clocked out -->
      <% if current_user.shifts.any? && !current_user.clocked_in  %>
        <%= render 'table' %>
      <% end %>

    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClockInApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather|Noto+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  </head>

  <body>
    <div class="navbar">
      <div class="nav-links"><p>
        <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %>
          <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
        <% end %>
        </p></div>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
    </div>
    <div class="main-container">
      <%= yield %>
    </div>
  </body>
</html>